In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('global_power_plant_database.csv')
df.head()

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,url,geolocation_source,wepp_id,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.00,32.3220,65.1190,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009793,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.00,34.5560,69.4787,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009795,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.00,34.6410,69.7170,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009797,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,GEODB0040536,11.55,34.4847,70.3633,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009787,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,Northwest Kabul Power Plant Afghanistan,GEODB0040540,42.00,34.5638,69.1134,Gas,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,NaN,2017.0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(29910, 24)

In [4]:
df.nunique()

country                       164
country_long                  164
name                        29538
gppd_idnr                   29910
capacity_mw                  5558
latitude                    27606
longitude                   28427
primary_fuel                   15
other_fuel1                    12
other_fuel2                    11
other_fuel3                     7
commissioning_year           2028
owner                        9565
source                        865
url                          4869
geolocation_source             27
wepp_id                     15399
year_of_capacity_data          10
generation_gwh_2013          5970
generation_gwh_2014          6310
generation_gwh_2015          6906
generation_gwh_2016          7439
generation_gwh_2017          8122
estimated_generation_gwh    11784
dtype: int64

In [5]:
df.isna().sum()

country                         0
country_long                    0
name                            0
gppd_idnr                       0
capacity_mw                     0
latitude                        0
longitude                       0
primary_fuel                    0
other_fuel1                 27947
other_fuel2                 29607
other_fuel3                 29806
commissioning_year          13607
owner                       10379
source                         15
url                            18
geolocation_source            419
wepp_id                     13529
year_of_capacity_data       16167
generation_gwh_2013         22914
generation_gwh_2014         22470
generation_gwh_2015         21766
generation_gwh_2016         20939
generation_gwh_2017         20697
estimated_generation_gwh     8119
dtype: int64

In [6]:
df_country=df.groupby(['country_long']).size().sort_values(0, ascending=False).reset_index()
df_country.head()

               country_long     0
0  United States of America  8686
1                     China  3041
2            United Kingdom  2536
3                    Brazil  2340
4                    France  2017

In [7]:
df_country_fuel=df.groupby(['country_long','primary_fuel']).size().sort_values(0, ascending=False).reset_index()
df_country_fuel.head()

               country_long primary_fuel     0
0  United States of America        Solar  2290
1  United States of America          Gas  1741
2  United States of America        Hydro  1457
3            United Kingdom        Solar  1092
4  United States of America         Wind  1043

In [8]:
df2=df.fillna('0')
df2_fuel=df2.groupby(['primary_fuel','other_fuel1','other_fuel2','other_fuel3']).size().sort_values(0, ascending=False).reset_index()
df2_fuel.head()

  primary_fuel other_fuel1 other_fuel2 other_fuel3     0
0        Hydro           0           0           0  7152
1        Solar           0           0           0  5902
2         Wind           0           0           0  5179
3          Gas           0           0           0  2985
4          Oil           0           0           0  2085

In [9]:
df2[(df2['generation_gwh_2013']!='0')&(df2['generation_gwh_2014']!='0')&(df2['generation_gwh_2015']!='0')&(df2['generation_gwh_2016']!='0')&(df2['generation_gwh_2017']!='0')].shape

(6817, 24)

In [10]:
df2[(df2['generation_gwh_2013']!='0')|(df2['generation_gwh_2014']!='0')|(df2['generation_gwh_2015']!='0')|(df2['generation_gwh_2016']!='0')|(df2['generation_gwh_2017']!='0')].shape

(10023, 24)

In [11]:
df2[(df2['generation_gwh_2013']!='0')|(df2['generation_gwh_2014']!='0')|(df2['generation_gwh_2015']!='0')|(df2['generation_gwh_2016']!='0')|(df2['generation_gwh_2017']!='0')].head()

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,url,geolocation_source,wepp_id,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
303,AUS,Australia,Albany Wind Farm,AUS0000065,21.6,-35.0641,117.7977,Wind,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1049129,0,89.5953,102.643,96.5556,95.8728,85.9003,0
305,AUS,Australia,Angaston,AUS0000232,50.0,-34.5034,139.0246,Oil,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1065303,0,0,0,1.65306,5.30083,7.64972,526.453
306,AUS,Australia,Anglesea,AUS0000114,165.0,-38.3861,144.1828,Coal,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1069504,0,1095.68,1239.96,1260.26,167.88,0,0
307,AUS,Australia,Appin (Mine),AUS0000264,55.6,-34.2082,150.7722,Gas,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1011059,0,204.804,238.294,163.584,158.933,64.5347,0
309,AUS,Australia,Awaba,AUS0000049,1.1,-33.0250,151.5497,Waste,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1088658,0,7.65528,8.33861,9.1725,8.83,8.08556,0

In [12]:
df2[(df2['generation_gwh_2013']!='0')&(df2['generation_gwh_2014']!='0')&(df2['generation_gwh_2015']!='0')&(df2['generation_gwh_2016']!='0')&(df2['generation_gwh_2017']!='0')].head()

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,url,geolocation_source,wepp_id,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
303,AUS,Australia,Albany Wind Farm,AUS0000065,21.6,-35.0641,117.7977,Wind,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1049129,0,89.5953,102.643,96.5556,95.8728,85.9003,0
307,AUS,Australia,Appin (Mine),AUS0000264,55.6,-34.2082,150.7722,Gas,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1011059,0,204.804,238.294,163.584,158.933,64.5347,0
309,AUS,Australia,Awaba,AUS0000049,1.1,-33.0250,151.5497,Waste,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1088658,0,7.65528,8.33861,9.1725,8.83,8.08556,0
310,AUS,Australia,Bairnsdale,AUS0000081,94.0,-37.8429,147.5639,Gas,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1049309,0,132.457,154.886,149.821,197.541,168.524,0
311,AUS,Australia,Ballarat Base Hospital,AUS0000113,3.0,-37.5596,143.8469,Gas,0,0,...,http://services.ga.gov.au/site_3/rest/services...,Australian Renewable Energy Mapping Infrastruc...,1010684,0,4.19444,4.21306,5.07944,6.83139,6.66333,0